Fixed installation script for mac.
* `set -e` was causing maybe_install to fail when a package was not installed. `which $1` was returning an error when the package was not installed.
* Did not make any changes to Linux install function.
* Getting an error installing poppler:
    ==> Installing gdal dependency: poppler
    Error: Cannot install poppler because conflicting formulae are installed.
    pdftohtml: because poppler, pdftohtml, pdf2image, and xpdf install conflicting executables
This error is unrelated to the script as it is reproducible using manual install steps. I have not been able to resolve this error yet.